### ISSUE TITLE
Misuse of `alias()`?

### ISSUE THREAD

**Issue by LeoniePhiline** [DerekStride/tree-sitter-sql#101]
I noticed that while creating syntax queries for hive statements.

I found that some uses of `alias()` (see https://tree-sitter.github.io/tree-sitter/creating-parsers#the-grammar-dsl) appear questionable to me, and I wanted to check with you.

# 1. Doubts: `(identifier)` for builtin functions

In both the following builtin functions, the function name keyword is replaced in the AST with `identifier`. I just wanted to check if that's really intentional?

Isn't an `(identifier)` rather identifying a application-domain-specific item, such as a table or field - rather than a builtin SQL feature keyword?

At first sight, not only `(identifier)` is wrong in this case, but the entire `field('name', ...)` should just be replaced by `$.keyword_cast` and `$.keyword_count`. 

_However,_ `field('name', ...)` gives compatibility with the generic `(invocation)` (https://github.com/DerekStride/tree-sitter-sql/blob/393e0d35aad922a3bf4faa4ceccad2e401f7b2ab/grammar.js#L1378-L1381), where a `field` is necessary to extract the function name -- so it's probably only the `(identifier)` alias that is to be removed.

**✅ Done so in e4e43ba742a2ee88cbb24dbf305a7daadd583873 and eac9da216bff9a377738637649ea2ef32fd021bb** 

## 1.1. `CAST`

https://github.com/DerekStride/tree-sitter-sql/blob/393e0d35aad922a3bf4faa4ceccad2e401f7b2ab/grammar.js#L1341-L1350

**✅ Fixed in e4e43ba742a2ee88cbb24dbf305a7daadd583873 _fix: Remove identifier alias from cast builtin function_ - PR #102**

## 1.2. `COUNT`

https://github.com/DerekStride/tree-sitter-sql/blob/393e0d35aad922a3bf4faa4ceccad2e401f7b2ab/grammar.js#L1357-L1362

**✅ Fixed in eac9da216bff9a377738637649ea2ef32fd021bb  _fix: Remove identifier alias from count builtin function_ - PR #102**

# 2. Misuse? String literals as `(identifier)`

https://github.com/DerekStride/tree-sitter-sql/blob/393e0d35aad922a3bf4faa4ceccad2e401f7b2ab/grammar.js#L980-L988

Shouldn't these rather be `alias($._literal_string, $.literal)`?

**✅ Fixed in 4216ecf07b4350b2068c5a418cf6c9b790f4ecf9 _fix: Replace identifier with literal for hive storage location and cache pool_ - PR #102**

`';'`, `'"'`, `'\n'` and `'/path/data'` in the Hive `CREATE TABLE` test end up as identifier tree item, while they clearly are literals:

![grafik](https://user-images.githubusercontent.com/22329650/219879037-b7abe021-9104-40e3-921a-c9a39c97bb45.png)

See also `LOCATION` under https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-table-hiveformat.html#parameters 

## 2.1 Update: `';'`, `'"'` and `'\n'` do not show up in the AST at all

https://github.com/DerekStride/tree-sitter-sql/blob/393e0d35aad922a3bf4faa4ceccad2e401f7b2ab/test/corpus/create.txt#L967-L1029

**✅ Fixed in d2f0f6695fffa4ec1c81fc2060eddf83161f9ee3 _ feat: Add AST-fields for row terminated/escaped-by and lines terminated-by-_ PR #102**

_Field names from: https://spark.apache.org/docs/latest/sql-ref-syntax-hive-format.html_

**Comment by LeoniePhiline** [comment]
(I'm working on a small PR.)

**Comment by DerekStride** [comment]
> However, field('name', ...) gives compatibility with the generic (invocation) (

You guessed correctlty, I initially setup `count` to be compatible with invocation but I think you're right that we shouldn't alias it to an identifier and instead expose the keyword named node 👍 

The rest of the changes look good to me too
