### ISSUE TITLE
Between expression or parentheses within case when context are not parsed correctly

### ISSUE THREAD

**Issue by Appalled** [DerekStride/tree-sitter-sql#133]
Tree-sitter-sql is really great, while I found some legal queries aren't paresed correctly. Would you mind checking them? 
The problems occur when 'between expression' or 'parentheses'  are surrounded by case when statement, here are two examples: 
```
SELECT 
a.*,
case when a.col BETWEEN 0 AND 1 then 1
when a.col >=1 then 0
end as col2
FROM tb_name a
;


SELECT
  a.*,
  CASE WHEN a.col_1 >= 100 THEN 0 ELSE 1 END AS col_a,
  CASE WHEN (a.col_1 >= 100) THEN 0 ELSE 1 END AS col_b
  CASE WHEN ((a.col_0 >= 1) AND (a.col_1 >= 100)) THEN 0
  END AS col_c
FROM
  tb_name a
WHERE
  ((a.col_0 >= 1) AND (a.col_1 >= 100))
;


```

**Comment by matthias-Q** [comment]
@Appalled thanks for reporting. Should be fixed now.

**Comment by Appalled** [comment]
> 

thanks. It works well. I run these quries in sparksql or presto.
