### ISSUE TITLE
T-SQL Alter Table

### ISSUE THREAD

**Issue by esetnik** [DerekStride/tree-sitter-sql#135]
TSQL:
```sql
ALTER TABLE Class_Session
ADD
type varchar(255) NOT NULL DEFAULT ('online');
```

Error:
```
Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but " " found. (sql)
```

Expected:
No error, this is valid sql

<img width="669" alt="image" src="https://user-images.githubusercontent.com/664434/230105485-13133413-832b-4474-a095-cc799a7dc8a0.png">

**Comment by matthias-Q** [comment]
The SQL statement works fine for my:
![image](https://user-images.githubusercontent.com/35303817/230116418-0939ba0b-c6ef-4526-9909-5447da0e89c2.png)

Can you update the grammar on your machine?

**Comment by esetnik** [comment]
Hmm. I am using the latest parser from `nvim-treesitter`. I believe it is https://github.com/nvim-treesitter/nvim-treesitter/commit/411e771d511442ab81670701f5c830f6c74aadd7. I'm not too familiar with how to update grammar directly. Can you clarify how I should do that?

**Comment by esetnik** [comment]
I apologize the error appears to be coming from https://github.com/fannheyward/coc-sql and not tree-sitter-sql

**Comment by matthias-Q** [comment]
OK, no problem. Upon further investigation, T-SQL seems to support to add multiple columns in one alter table statement (like in your screenshot).
This parse aims to be permissive and we mostly consider MySQL, MariaDB, PostgreSQL and a some Hive statements. These dialect do not support this style of altering tables.

If you want you can reopen it. I definately get an error for statements like:
```
alter table classname 
add
col1 varchar(255) not null default('empty'),
col2 varchar(255) not null default('empty2');
```

**Comment by esetnik** [comment]
Ok in that case we should probably reopen this one as well since there appear to be two separate issues in the same statement. The issue I originally reported was fixed in https://github.com/taozhi8833998/node-sql-parser/issues/1372. Thanks for your help! Happy to test out a potential solution.
