### ISSUE TITLE
Parsing nested CTEs

### ISSUE THREAD

**Issue by Gelio** [DerekStride/tree-sitter-sql#165]
I found that the following valid PostgreSQL query involving nested CTEs is not parsed correctly by this grammar:

```sql
WITH top_cte AS (
  WITH nested_cte AS (
    SELECT 1 as one, 2 as two
  )
  SELECT one, two
  FROM nested_cte
)
SELECT *
FROM top_cte;
```

Received AST:

```
(program
  (ERROR
    (statement
      (keyword_with)
      (cte
        (identifier)
        (keyword_as)
        (ERROR
          (keyword_as))
        (statement
          (select
            (keyword_select)
            (select_expression
              (term
                (literal)
                (keyword_as)
                (identifier))
              (term
                (literal)
                (keyword_as)
                (identifier))))))
      (select
        (keyword_select)
        (select_expression
          (term
            (field
              (identifier)))
          (term
            (field
              (identifier)))))
      (from
        (keyword_from)
        (relation
          (object_reference
            (identifier))))))
  (statement
    (select
      (keyword_select)
      (select_expression
        (term
          (all_fields))))
    (from
      (keyword_from)
      (relation
        (object_reference
          (identifier))))))
```

[This SO answer](https://stackoverflow.com/questions/1413516/can-you-create-nested-with-clauses-for-common-table-expressions) says nested CTEs are not valid, at least for T-SQL. I found that PostgreSQL has no problem executing that query, though:

![image](https://github.com/DerekStride/tree-sitter-sql/assets/889383/aabe3b7e-eb2f-484d-95fa-3bd2411fe8ea)

**Comment by matthias-Q** [comment]
@dmfay I was thinking that this should be fairly simple. I tested to add `$._cte` to the choices in https://github.com/DerekStride/tree-sitter-sql/blob/ddd1763a4c2dbe97477ff36168ebe28a8da373a7/grammar.js#L609. In my mind this should work, but I still get an error. Any ideas?

**Comment by Gelio** [comment]
Thank you both @matthias-Q and @dmfay for fixing it so fast!
