### ISSUE TITLE
Adding missing SQL Server keywords

### ISSUE THREAD

**Issue by RAV64** [DerekStride/tree-sitter-sql#191]
Would it be possible to have this parser also include [SQL Server specific keywords](https://learn.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-ver16), for example:

NVARCHAR
NCHAR
DATETIME2
DATETIMEOFFSET
SMALLDATETIME
TIME
SMALLMONEY
VARBINARY
IMAGE

Also, some functions are missing, for example: 

OBJECT_ID

I assume others too, this is the only one I checked :)

I can also write a PR for this if that's an issue.

Thanks! ❤️

**Comment by dmfay** [comment]
types absolutely! As for functions, we've been moving away from special-casing those -- for example, there's no standalone `count` or `rank` anymore. `object_id` should already resolve as an `invocation` afaik, and that'll have the `name` field.

**Comment by matthias-Q** [comment]
NVARCHAR/NCHAR as a type is easy, but referencing it might be a bit more challenging:
```
SELECT * FROM tab WHERE  col = N'BLUBB' 
```
