### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by rien** [DerekStride/tree-sitter-sql#195]
Hi, is it possible to publish this grammar on npm?

There is already a `tree-sitter-npm` package published (from this repository: https://github.com/m-novikov/tree-sitter-sql/), however it has not been updated in 2 years and this grammar seems to be more complete and active.

**Comment by matthias-Q** [comment]
Pretty sure we can do that. I have never published anything on npm, but maybe @dmfay or  @DerekStride have?

**Comment by dmfay** [comment]
I have, but Max Novikov's version owning the `tree-sitter-sql` name means we would have to coordinate with him (and first of all he would have to agree) to take it over.

npm has namespaced scopes (@org/package-name) which would get around that, but I'd want to publish under something like `@tree-sitter`. The project doesn't use scopes unfortunately, and we aren't even listed in the [parsers directory](https://tree-sitter.github.io/tree-sitter/) yet.

**Comment by matthias-Q** [comment]
@DerekStride @dmfay how do we proceed here?

**Comment by dmfay** [comment]
on the immediate issue of publishing to npm, either we (and by we I mean "probably Derek", since it's his repo 😄) talk to Max, or we (in a slightly more general sense) decide whether we're okay publishing this as tree-sitter-sql-general or something.

**Comment by DerekStride** [comment]
> The project doesn't use scopes unfortunately, and we aren't even listed in the [parsers directory](https://tree-sitter.github.io/tree-sitter/) yet.

I have an open PR to add us to the parser list but it seems they batch these kind of changes & merge them periodically https://github.com/tree-sitter/tree-sitter/pull/2119. 

How do we feel about a scoped package under my username to match the github project? e.g. `npm install @derekstride/tree-sitter-sql`

**Comment by rien** [comment]
Thanks for putting effort into publishing this package on NPM :heart: 

However, in our project, we've decided to start vendoring our parsers (aggregating all the parsers we use in our own package), so for our use case this isn't needed anymore. I'm sure it's still a good thing to publish this parser anyway, so it lowers the barrier for others to use this.

**Comment by DerekStride** [comment]
The package is live! https://www.npmjs.com/package/@derekstride/tree-sitter-sql

I had a typo in the CI workflow 🤦 I fixed it but had to publish it manually. Next time we publish it should work 🤞
