### ISSUE TITLE
Additional dollar quote support

### ISSUE THREAD

**Issue by rliebz** [DerekStride/tree-sitter-sql#217]
Using Postgres syntax, I've found a couple situations where valid dollar quote syntax is not parsed correctly.

One is that dollar quotes do not seem to be respected in `COMMENT` statements:

```sql
COMMENT ON SCHEMA "my_schema"
  IS $$My Schema Comment$$;
```

Based on my read of [the Postgres docs](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING), I would assume dollar-quoted strings are valid anywhere regular strings are. I'm not sure what other situations this would pop up in, but it might not be an issue particular to comment statements.

The other is that the optional tags do not seem to be supported. For example, this works:

```sql
CREATE FUNCTION foo(TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
AS $$
  RETURN TRUE
$$;
```

But this equivalent function does not:

```sql
CREATE FUNCTION foo(TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
AS $function$
  RETURN TRUE
$function$;
```

**Comment by antoineB** [comment]
Hello I suspect you haven't run the `make compile` command the file `parser.c` is not up to date.

**Comment by rliebz** [comment]
You're so right. Appreciate the quick response and apologies for the false alarm.
