### ISSUE TITLE
Highlighting queries rely on neovim-only `lua-match`

### ISSUE THREAD

**Issue by Colonial-Dev** [DerekStride/tree-sitter-sql#220]
Specifically, the [rules for matching literal numbers and floats.](https://github.com/DerekStride/tree-sitter-sql/blob/764c1bd5ea856dd7db5171783e442321dc3e041f/queries/highlights.scm#L36)

As far as I'm aware, `lua-match` is exclusive to Neovim's implementation of `tree-sitter` based syntax highlighting. This means that highlighting numeric literals will silently fail when using something like the standard `tree-sitter-highlight` package.

I *think* changing them to use `match` with these regexes should work the same way. However, I've never created a `tree-sitter` grammar, so I figured it would be best left to your discretion.

- `^\d+$` for integers.
- `^[-]?\d*\.\d*$` for floats.

These worked fine when tested in [Rustexp](https://rustexp.lpil.uk/).

**Comment by matthias-Q** [comment]
Thanks for your comment. I think this query is not used anywhere. It is just for us that we make sure to provide a query for all of the keywords of the parser.

However, the regex for numbers has been changed recently and probably needs to be updated in the respective downstream packages (e.g. nvim-treesitter, helix...)

**Comment by Colonial-Dev** [comment]
> I think this query is not used anywhere.

I actually use it in my library [Inkjet](https://github.com/Colonial-Dev/inkjet) :sweat_smile: Since this grammar bills itself as targeted at `tree-sitter` rather than (say) Neovim, I think the highlighting queries should be maximally compatible if they're provided.

**Comment by matthias-Q** [comment]
fixed by #225

**Comment by Colonial-Dev** [comment]
Thanks a bunch!
