### ISSUE TITLE
Scanner.c is missing on npm, therefore preventing the package installation

### ISSUE THREAD

**Issue by JonathanxD** [DerekStride/tree-sitter-sql#231]
The [scanner.c](https://github.com/DerekStride/tree-sitter-sql/blob/a65f58c364f4051e14c54be06dfdb91b546d6e7f/src/scanner.c) file is missing on the published [npm package](https://www.npmjs.com/package/@derekstride/tree-sitter-sql?activeTab=code). This is causing the `npm install` to fail during the `node-gyp rebuild` step.

## Steps to reproduce

```sh
$ mkdir tree-sitter-sql
$ cd tree-sitter-sql
$ npm pack @derekstride/tree-sitter-sql@0.1.1
$ tar --strip-components=1 -xvf derekstride-tree-sitter-sql-0.1.1.tgz package/
$ npm install
```

The compilation step will fail with the following error:

```sh
make: *** No rule to make target 'Release/obj.target/tree_sitter_sql_binding/src/scanner.o', needed by 'Release/obj.target/tree_sitter_sql_binding.node'.  Stop.
```

But if you download the `scanner.c` manually, it'll work:

```sh
$ mkdir -p src/
$ curl -Lo src/scanner.c 'https://derek.stride.host/tree-sitter-sql/src/scanner.c'
$ npm install
```

I'm not well versed on the *npm publish* behavior, but I think this is being caused by [having `/src/` defined on `.gitignore`](https://github.com/DerekStride/tree-sitter-sql/blob/a65f58c364f4051e14c54be06dfdb91b546d6e7f/.gitignore#L12).

**Comment by steve-marmalade** [comment]
Could this be the cause of the following error I'm getting when opening a `.sql` file?

```
Error executing lua callback: Failed to load parser for language 'sql': uv_dlopen: /home/user/.local/share/nvim/site/pack/packer/start
/nvim-treesitter/parser/sql.so: undefined symbol: tree_sitter_sql_external_scanner_create
```

**Comment by DerekStride** [comment]
`v0.2.0` should have `scanner.c` included.

> Could this be the cause of the following error I'm getting when opening a .sql file?

I'm doubtful, neovim requests `scanner.c` by default:

https://github.com/nvim-treesitter/nvim-treesitter/blob/000f71842bf08840df1e70004b17507fa92b2fb7/lua/nvim-treesitter/parsers.lua#L1742

**Comment by JonathanxD** [comment]
> `v0.2.0` should have `scanner.c` included.
> 
> > Could this be the cause of the following error I'm getting when opening a .sql file?
> 
> I'm doubtful, neovim requests `scanner.c` by default:
> 
> [nvim-treesitter/nvim-treesitter@`000f718`/lua/nvim-treesitter/parsers.lua#L1742](https://github.com/nvim-treesitter/nvim-treesitter/blob/000f71842bf08840df1e70004b17507fa92b2fb7/lua/nvim-treesitter/parsers.lua#L1742)

Thank you!
