### ISSUE TITLE
Feature Request: Support for parameter placeholders

### ISSUE THREAD

**Issue by wilriker** [DerekStride/tree-sitter-sql#24]
Hi!

In my daily work I have to deal with literal SQL queries that contain parameter placeholders in 99% of the cases.
Is it possible/planned/not planned to add support for them? The drivers I use expect `?` as placeholder although there are other syntaxes.

Or is this something that can possibly be even added at the level of queries?

Cheers
Manuel

**Comment by DerekStride** [comment]
An example would be very helpful and you looking for something like parameterized queries?

```sql
SELECT *
FROM x
WHERE id = ?;
```

**Comment by wilriker** [comment]
> ```sql
> SELECT *
> FROM x
> WHERE id = ?;
> ```

That's exactly what I meant. 👍

**Comment by DerekStride** [comment]
Alright, it should be working now 🎉

**Comment by wilriker** [comment]
Thanks! I can confirm that `?` is now recognized as parameter!
