### ISSUE TITLE
Support for check constraints

### ISSUE THREAD

**Issue by rliebz** [DerekStride/tree-sitter-sql#247]
The parser does not currently seem to support check constraints, for example:

```sql
CREATE TABLE products (
    product_no integer,
    name text,
    price numeric CHECK (price > 0)
);
```

For reference: https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS

**Comment by matthias-Q** [comment]
If I have time I will take a look.
