### ISSUE TITLE
Bug: support SELECT from more than two tables

### ISSUE THREAD

**Issue by wilriker** [DerekStride/tree-sitter-sql#25]
As of right now a select like
```sql
SELECT *
FROM 
    Table1 a,
    Table2 b,
    ...
    TableN z
WHERE...
```
will result in an error on the table list. It does recognize both the first and the last table with its `name` and `table_alias` just fine but it does not recognize the table(s) in between.

**Comment by DerekStride** [comment]
This should be supported now, reopen the issue or create a new one if you have any trouble with it

**Comment by wilriker** [comment]
I can confirm it works as expected now. Thanks!
