### ISSUE TITLE
Publish on PyPI?

### ISSUE THREAD

**Issue by prurph** [DerekStride/tree-sitter-sql#269]
This grammar isn't available for installation in Python projects via `pip`. The tree-sitter team has a workflow [here](https://github.com/tree-sitter/workflows?tab=readme-ov-file#pypi-options); what do you think about adding this to the project to publish to PyPi? Thanks for considering!

**Comment by DerekStride** [comment]
Done! It's available here: https://pypi.org/project/tree-sitter-sql/0.3.5/

**Comment by prurph** [comment]
Wow what a fast response! Thank you so much!

**Comment by matthias-Q** [comment]
I just tried it out and 
```python
tree_sitter_sql.language()
```
returns an integer for me and not a `Language`

not sure if that is correct
