### ISSUE TITLE
Dbt Jinja

### ISSUE THREAD

**Issue by matthias-Q** [DerekStride/tree-sitter-sql#28]
Hi there, 
I am using this Treesitter grammar for a while now in neovim. I work a lot with dbt, which consists of sql files with some jinja blocks inside. Is there any change to get this included in the grammar (or at least ignored).
I have some (pg)SQL files which look really weird, e.g. the Syntax Highlighting stops in the middle of the file and TS reports and error (even without jinja blocks near the error location).

**Comment by dmfay** [comment]
The SQL grammar isn't really the place to detect anything other than SQL (even for the purpose of ignoring it). I think you might need something more along the lines of [this plugin](https://github.com/joker1007/vim-markdown-quote-syntax) that sets appropriate syntax highlighting for code blocks in markdown -- same principle at work.

**Comment by matthias-Q** [comment]
Thanks for the response. I will take a look at the plugin - maybe I can write a similar one for SQL with jinja.

I checked where the (not jinja related) errors in my sql occured and it is at a postgres specific syntax ( `columnname::date` or `cast(columnname as date)`

**Comment by DerekStride** [comment]
Since the `jinja` syntax would have to be it's own parser so I'll close this issue. I believe the cast syntax you mentioned should be fixed by #30.

To get the latest parser working in neovim we'd need to update the parser version: https://github.com/nvim-treesitter/nvim-treesitter/blob/94806bc5ce575d156fb6a08afa298dd4fdd41cca/lockfile.json#L302-L304

**Comment by matthias-Q** [comment]
Thanks for mentioning the injections. I will take a look at these.

Also thanks for fixing the Postgres specific problems. What is your policy on SQL dialects? Because i noticed a lot of TS errors in my SQL files. Do you want to have the grammar as dialect agnostic as possible?
