### ISSUE TITLE
Syntax Highlighting is broken for tree-sitter 0.24

### ISSUE THREAD

**Issue by jakob** [DerekStride/tree-sitter-sql#282]
When I use the command `tree-sitter highlight test.sql` with this grammar, I get the following error:
```
Error in query file "queries/highlights.scm"

Caused by:
    Query error at 151:4. Invalid node type keyword_min
```

(It works with tree-sitter 0.23.2, but it is broken in 0.24 or newer)

I believe it is caused by a new feature where `tree-sitter generate` removes unused rules. Since `keyword_max` is not used in the grammar, it is removed, and the highlight query fails because it uses an unknown node type.

**Comment by DerekStride** [comment]
closed by #285
