### ISSUE TITLE
Question: ANSI SQL?

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [DerekStride/tree-sitter-sql#4]
Hi Derek,

I had a few questions regarding your grammar:

1. I was wondering what source grammar you used to build the grammar file
2. Is this sql grammar ANSI SQL or some other dialect
3. How did you start writing this? Did you start with the grammar.js and was everything else generated using the parser generator?

**Comment by DerekStride** [comment]
Hi Prasanth,

1,2. I am mostly building this for the MySQL dialect but was using this [reference](https://forcedotcom.github.io/phoenix/index.html) to get a sense of the general structure of SQL syntax.
3. This is built on tree-sitter more details on how it works can be found [here](https://tree-sitter.github.io/tree-sitter/creating-parsers), but yes you essentially just have to write the `grammar.js` file and the tests and the rest is generate when running `tree-sitter-cli generate`

**Comment by sfc-gh-pkommini** [comment]
Is the grammar.json also autogenerated?

**Comment by DerekStride** [comment]
> Is the grammar.json also autogenerated?

Yup!

**Comment by sfc-gh-pkommini** [comment]
Thanks a ton for answering :)
