### ISSUE TITLE
Question: Is recursion supported in this grammar?

### ISSUE THREAD

**Issue by sfc-gh-nlele** [DerekStride/tree-sitter-sql#5]
Hello, we were wondering if this grammar supports recursion (especially for multiple queries)?

For example:

select * from foo where bar > (select foobar from barfoo);

Will something like this be supported by the grammar?

**Comment by DerekStride** [comment]
At the moment I don't think the grammar supports that. However, it shouldn't be too hard to add. I put up a PR for it here: https://github.com/DerekStride/tree-sitter-sql/pull/6
