### ISSUE TITLE
Support `BEGIN ... END` blocks

### ISSUE THREAD

**Issue by ObserverOfTime** [DerekStride/tree-sitter-sql#52]
`BEGIN ... END` blocks are used in [MySQL](https://dev.mysql.com/doc/refman/8.0/en/begin-end.html) and [MSSQL](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/begin-end-transact-sql?view=sql-server-ver16).

Here's a minimal example (which GitHub also fails to highlight properly):
```sql
BEGIN
    CREATE TABLE FOO (bar INT);
END;
```

```
keyword_begin [0, 0] - [0, 5]
ERROR [1, 4] - [2, 3]
  keyword_table [1, 11] - [1, 16]
```

**Comment by DerekStride** [comment]
Is this something you'd be interested in tackling? PRs are always welcome.

**Comment by ObserverOfTime** [comment]
Maybe I can try when I have some time to look into it.

**Comment by DerekStride** [comment]
I'll close this for now, re-open it / open a new issue if you need more functionality added 👍
