### ISSUE TITLE
Support for Hive specific statements

### ISSUE THREAD

**Issue by matthias-Q** [DerekStride/tree-sitter-sql#69]
Hi,
would it be possible to support Hive specific commands such `STORED AS PARQUET` or `COMPUTE STATS`?
This SQL extensions are supported by many databases these days (Redshift, Impala, Snowflake, Datafusion)

I would create a PR for that, if you are ok with that and once I have collected more examples.

Cheers,
Matt

**Comment by matthias-Q** [comment]
It is a while since I have worked on this project. Do I still have to check in the parser.c and grammar.json/node-types.json? or is it sufficient to just check in the grammar.js?

**Comment by DerekStride** [comment]
You should still check in the generated files for now we have a `.gitattributes` file to hide them from the GitHub diffs.

**Comment by LeoniePhiline** [comment]
How do I trigger generating the files in `src/`?

**Comment by matthias-Q** [comment]
@LeoniePhiline, I am using the rust based CLI for building the parser.c. You can install it via `cargo install tree-sitter-cli`

**Comment by LeoniePhiline** [comment]
Thanks a lot!

**Comment by LeoniePhiline** [comment]
@matthias-Q What do you think about the above build errors? They stem from use of `tree-sitter generate` CLI.

**Comment by LeoniePhiline** [comment]
I got `v19.5.0`. 

But, after all, it seems to be irrelevant: `node-gyp rebuild` appears to be unnecessary to work on the grammar?! 🤔
