### ISSUE TITLE
Some more MariaDB syntax missing or inconsistent highlight

### ISSUE THREAD

**Issue by LeoniePhiline** [DerekStride/tree-sitter-sql#71]
Using 4fe05b2d81565ddb689d2f415e07afdacc515c52

```sql
CREATE TABLE publications(
    `uid` INT AUTO_INCREMENT NOT NULL,
    `pid` INT DEFAULT 0 NOT NULL,
    `tstamp` INT UNSIGNED DEFAULT 0 NOT NULL,
    `crdate` INT UNSIGNED DEFAULT 0 NOT NULL,
    `cruser_id` INT UNSIGNED DEFAULT 0 NOT NULL,
    `deleted` SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
    `hidden` SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
    `notes` TEXT DEFAULT NULL,
    `code` VARCHAR(3) DEFAULT '' NOT NULL,
    `name` VARCHAR(100) DEFAULT '' NOT NULL,
    `frequency` SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
    `editions` INT UNSIGNED DEFAULT 0 NOT NULL,
    `subscription_types` INT UNSIGNED DEFAULT 0 NOT NULL,
    `methods` INT UNSIGNED DEFAULT 0 NOT NULL,
    INDEX `parent`(pid),
    PRIMARY KEY(uid)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
```
![image](https://user-images.githubusercontent.com/22329650/214721214-e7923c5a-d095-4ab1-8c08-73a31574ed49.png)

1. `NOT` is sometimes lit, sometimes it isn't. ✅ _Fixed by  #73_
2. `UNSIGNED` might be something to highlight as keyword?  ✅ _Fixed by  #88_
3. `INDEX` should be a keyword like `KEY` ✅ _Fixed by  #77_
4. `DEFAULT CHARACTER SET`, `COLLATE` and `ENGINE` all keywords. ✅ _Fixed by  #77_

---

```sql
CREATE TABLE some_table(
    `code` VARCHAR(9) DEFAULT '' NOT NULL,
    `name` VARCHAR(100) DEFAULT '' NOT NULL,
    `published_at` DATE DEFAULT '0000-00-00' NOT NULL,
    INDEX `parent`(pid),
    INDEX `parent_publication`(publication, hidden, deleted),
    INDEX `range`(publication, published_at),
    PRIMARY KEY(uid)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
```

![image](https://user-images.githubusercontent.com/22329650/214721741-c1d9e755-2a55-4fec-9d54-2757449e13a7.png)

1. All string literals, such as `''` and `'0000-00-00'` should probably be yellow, as the varchar lengths are, and as other string literals are, e.g. in `UPDATE ... SET field = 'string literal'`. ✅ _Fixed by  #73_
2. `INDEX` etc. as above. ✅ _Fixed by  #77_

---

```sql
ALTER TABLE `lesson` ADD editions INT DEFAULT 0 NOT NULL;
```

![image](https://user-images.githubusercontent.com/22329650/214722604-9024e3c8-b7da-4889-ba60-56d172a80e50.png)

1. `INT` is not recognized as keyword in this position. ✅ _Fixed by  #80_
2. integer `DEFAULT` values are white (not highlighted as literal), where I would have expected them to be yellow (literal).  ✅ _Fixed by  #73_

---

```sql
DROP INDEX `parent_method` ON site;
CREATE INDEX `parent_method` ON site (pid, deleted, parent_method, hidden);
```

![image](https://user-images.githubusercontent.com/22329650/214723097-8342f29d-d5f1-42b7-9c66-8a23ebdc3d9f.png)

1. `INDEX` after `DROP` is not recognized as keyword.  ✅ _Fixed by  #96_
---

```sql
UPDATE site
  SET publication = 1
  WHERE type = 'method' AND identifier = "some_identifier";
```

![image](https://user-images.githubusercontent.com/22329650/214723368-88332bc4-8e32-4d53-9c3b-bd3a87e7df68.png)

1. String literals without highlight in `UPDATE ... SET ... WHERE ...` in `WHERE`-position. (Either quote style.) ✅ _Fixed  - must be caused by a previous parse error in the same file._
2. The numeric literal in `SET`-position should also be yellow rather than white. ✅ _Fixed by  #73_

---

```sql
ALTER TABLE site 
  RENAME COLUMN access_groups TO subscription_types;
```

![image](https://user-images.githubusercontent.com/22329650/214723850-e26e46c6-2189-4efc-8f09-dd0bef0792f6.png)

1. `TABLE` in `ALTER TABLE` not recognized as keyword. ✅ _Fixed  - must be caused by a previous parse error in the same file._

---

```sql
ALTER TABLE `fe_groups` ADD `tx_digibordauthentication_code` VARCHAR(10) DEFAULT '' NOT NULL;
ALTER TABLE `fe_groups` ADD `tx_digibordauthentication_access_model` INT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `fe_groups` ADD `tx_digibordauthentication_allow_historical` INT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `fe_groups` ADD `tx_digibordauthentication_allow_media_archive` INT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `fe_groups` ADD `tx_digibordauthentication_seasonal_access_first` SMALLINT UNSIGNED DEFAULT 1 NOT NULL;
ALTER TABLE `fe_groups` ADD `tx_digibordauthentication_seasonal_access_last` SMALLINT UNSIGNED DEFAULT 1 NOT NULL;
ALTER TABLE `fe_groups` ADD `tx_digibordauthentication_seasonal_restrict_auth` SMALLINT UNSIGNED DEFAULT 1 NOT NULL;
ALTER TABLE `fe_groups` ADD tx_digibordauthentication_notes TEXT DEFAULT NULL;
ALTER TABLE `fe_groups` ADD tx_digibordauthentication_publication INT UNSIGNED DEFAULT 0 NOT NULL;

CREATE INDEX `publication` ON `fe_groups` (pid, tx_digibordauthentication_publication);

ALTER TABLE `fe_groups` CHANGE `tx_digibordauthentication_site` `tx_digibordauthentication_site` INT UNSIGNED DEFAULT 0 NOT NULL;
```

![image](https://user-images.githubusercontent.com/22329650/214724722-d5864a5f-8ee2-4a96-ae6e-206c29aa3ecd.png)

1. Inconsistent highlight for `ADD` ✅ _Fixed by  #80_
2. No highlight for `ON` at `CREATE INDEX ... ON` ✅ _Fixed by  #80 (parse error in the `ALTER TABLE` above)_
3. No highlight for `CHANGE` in `ALTER TABLE ... CHANGE`  ✅ _Fixed by  #99_
4. Datatypes (except for `TEXT`!) and `UNSIGNED` not recognized as highlight (already mentioned further above). ✅ _Fixed by  #80 (parse error in the `ALTER TABLE` above)_ +  ✅ _Fixed by  #99_
5. Default values not recognized as literals (already mentioned further above). ✅ _Fixed by  #73_
 
---

```sql
ALTER TABLE some_table 
ADD some_field INT UNSIGNED NOT NULL DEFAULT '0'
AFTER some_other_field;
```

![grafik](https://user-images.githubusercontent.com/22329650/214743483-e16f1ddd-e9c6-44a5-9403-b83fd3029e52.png)

1. `AFTER` not highlighted.  ✅ _Fixed by  #99_
2. `INT UNSIGNED` and `'0'` as mentioned above.
  - `INT` ✅ _Fixed by  #80_
  - `UNSIGNED`   ✅ _Fixed by  #88_
  - `'0'`  ✅ _Fixed by  #73_

**Comment by matthias-Q** [comment]
Some of the issues occur, because keywords are missing completely like
* `UNSIGNED`
* `CHANGE`

It is a bit more helpful to check the AST directly and look where the parsing error actually happens.

**Comment by LeoniePhiline** [comment]
I've updated all sub-issues in the OP with references to done or pending fixes.

**Comment by DerekStride** [comment]
Am I correct in marking this as closed now? Looks like everything has been fixed & merged thank you all for the help in getting this all done. Everyone's been super helpful and active, I appreciate it ❤️ 

That said, re-open if I've missed anything!

**Comment by LeoniePhiline** [comment]
I think we’re good with this one! :) Thank you as well!
