### ISSUE TITLE
Comments are not terminated by newline

### ISSUE THREAD

**Issue by LeoniePhiline** [DerekStride/tree-sitter-sql#72]
Example:
```sql
--
-- Table structure for table 'tx_digibordauthentication_activity_log'
--
CREATE TABLE tx_digibordauthentication_activity_log
(
  uid         int(11) unsigned    NOT NULL auto_increment,
);
```

![image](https://user-images.githubusercontent.com/22329650/215206181-38c7a701-b63b-4f5b-b59d-91ae5afe6742.png)

Adding a space to the `--` above `CREATE` does not help.

Adding any letter does help, however:

```sql
--
-- Table structure for table 'tx_digibordauthentication_activity_log'
-- X
CREATE TABLE tx_digibordauthentication_activity_log
(
  uid         int(11) unsigned    NOT NULL auto_increment,
);
```

![image](https://user-images.githubusercontent.com/22329650/215206391-c42c9295-e1f5-458b-af60-1e48eab0abaa.png)

Could the problem be this regex being eager-matching / greedily-matching?

https://github.com/DerekStride/tree-sitter-sql/blob/main/grammar.js#L331

Could a lazy `/.*?\n/` do the trick?

**Comment by DerekStride** [comment]
> Could a lazy /.*?\n/ do the trick?

Yeah I think that would do it, want to open a PR for it?

**Comment by LeoniePhiline** [comment]
I tried locally and couldn't make it work. Am I doing something wrong? 

Here's what I do, using helix:
- In `$HELIX_RUNTIME/grammars` run `rm sql.so`
- In `$HELIX_RUNTIME/grammars/sources/sql` edit `grammar.js`
- Run `hx --grammar build`
- Open a fresh hx instance to check if it changed something.

It confirms rebuilding sql - but my changes to `grammar.js` appear to have no effect at all. (Even if I change `"--"` for something bogus, comments in the SQL file are still highlighted as comments.)

Could you try verifying the fix?

**Comment by matthias-Q** [comment]
I have tested it on my machine and the suggested regex does not fix the issue:

`    comment: _ => seq('--', /.*?\n/),`

with following SQL:
```SQL
--
CREATE TABLE tx_digibordauthentication_activity_log
(
  uid int(11) unsigned NOT NULL auto_increment,
);

```

produces this AST:
```
(program [0, 0] - [5, 0]
  (comment [0, 0] - [2, 0])
  (ERROR [2, 0] - [4, 2]
    (keyword_not [3, 23] - [3, 26])
    (keyword_null [3, 27] - [3, 31])
    (keyword_auto_increment [3, 32] - [3, 46])))
playground.sql	0 ms	(ERROR [2, 0] - [4, 2])
```

**Comment by dmfay** [comment]
Tree-sitter regexes are single-line by default so I think the explicit newline is actually throwing it off. Other grammars like [JS](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/grammar.js#L949), [Python](https://github.com/tree-sitter/tree-sitter-python/blob/master/grammar.js#L1037) or [Bash](https://github.com/tree-sitter/tree-sitter-bash/blob/master/grammar.js#L535) use `.*` sans newline for single-line comments; [the Java grammar](https://github.com/tree-sitter/tree-sitter-java/blob/master/grammar.js#L1173) has what seems like an unnecessary negative (anything but a newline) character class.

I've created https://github.com/DerekStride/tree-sitter-sql/pull/74 , please check it out!

**Comment by LeoniePhiline** [comment]
Fixed https://github.com/DerekStride/tree-sitter-sql/pull/74
