### ISSUE TITLE
`UNSIGNED` is missing

### ISSUE THREAD

**Issue by LeoniePhiline** [DerekStride/tree-sitter-sql#79]
Causing queries like this to fail:

```sql
SELECT CAST("1" AS UNSIGNED INTEGER);
```
_Example source: https://mariadb.com/kb/en/cast/ ._

Tree:

![image](https://user-images.githubusercontent.com/22329650/216116945-d9a422ef-5fba-44e6-b512-abc67b4ef691.png)

`'unsigned'` does not appear in `grammar.js` at all and should probably be a keyword and part of the numeric type declarations.

**Comment by matthias-Q** [comment]
I take this one.

**Comment by LeoniePhiline** [comment]
Fixed by #86 & #88
